sudo: required

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - libboost-dev

# Build your code e.g. by calling make
script:
  - wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh
  - sudo sh cmake-3.16.2-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir
  - mkdir build && cd build
  - cmake -DETISS_BUILD_MANUAL_DOC=ON ..
  - make doc

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
