name: CI

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        config:
          - {name: "Linux", os: ubuntu-latest, cmakegen: "", tc: "riscv64-unknown-elf-gcc-8.3.0-2020.04.0-x86_64-linux-ubuntu14", tc-ext: ".tar.gz", unpack: "tar xf"}
          - {name: "Windows", os: windows-latest, cmakegen: "-G \"MinGW Makefiles\"", tc: "riscv64-unknown-elf-gcc-8.3.0-2020.04.0-x86_64-w64-mingw32", tc-ext: ".zip", unpack: "unzip"}
          - {name: "Mac", os: macOS-latest, cmakegen: "", tc: "riscv64-unknown-elf-gcc-8.3.0-2020.04.0-x86_64-apple-darwin", tc-ext: ".tar.gz", unpack: "tar xf"}

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}

    steps:
    - uses: actions/checkout@v2

    - name: Requirements (Linux)
      if: matrix.config.name == 'Linux'
      run: |
        sudo apt-get install libboost-system-dev libboost-filesystem-dev

    - name: Requirements (Windows)
      if: matrix.config.name == 'Windows'
      shell: bash
      run: |
        choco install boost-msvc-14.1 wget unzip

    - name: Requirements (Mac)
      if: matrix.config.name == 'Mac'
      run: |
        brew install boost coreutils

    - name: Requirements
      shell: bash
      working-directory: ${{runner.workspace}}
      run: |
        wget https://static.dev.sifive.com/dev-tools/${{ matrix.config.tc }}${{ matrix.config.tc-ext }}
        ${{ matrix.config.unpack }} ${{ matrix.config.tc }}${{ matrix.config.tc-ext }}
        mv ${{ matrix.config.tc }} riscv-tc

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=../install

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target install

    - name: Setup tests
      working-directory: ${{runner.workspace}}/install/examples
      run: |
        cmake -E make_directory ${{runner.workspace}}/install/examples/SW/riscv/build
        cd SW/riscv/build
        cmake .. -DRISCV_ELF_GCC_PREFIX=../../../../../riscv-tc -DRISCV_ELF_GCC_BASENAME=riscv64-unknown-elf
        cmake --build . --config $BUILD_TYPE
        cd -
        cmake -E make_directory ${{runner.workspace}}/install/examples/SW/riscv_cpp/build
        cd SW/riscv_cpp/build
        cmake .. -DRISCV_ELF_GCC_PREFIX=../../../../../riscv-tc -DRISCV_ELF_GCC_BASENAME=riscv64-unknown-elf
        cmake --build . --config $BUILD_TYPE
        cd -
        cd bare_etiss_processor
        cmake -E make_directory ${{runner.workspace}}/install/examples/bare_etiss_processor/build
        cd build
        cmake ..
        cmake --build . --config $BUILD_TYPE

    - name: Test (Linux/Mac)
      working-directory: ${{runner.workspace}}/install/examples/bare_etiss_processor
      if: matrix.config.name == 'Linux' || matrix.config.name == 'Mac'
      shell: bash
      run: |
        ./run_helper.sh ../SW/riscv/build/riscv_example
        ./run_helper.sh ../SW/riscv/build/riscv_example gcc
        ./run_helper.sh ../SW/riscv_cpp/build/riscv_example
        ./run_helper.sh ../SW/riscv_cpp/build/riscv_example gcc
